name: Cli-core Buils

on:
  repository_dispatch:
    types: [ releaseCliCore ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    - run: npm ci
    - run: npm test
#   releseCli:
#     strategy:
#       matrix:
#         repo: ['LakshmiRavali/twilio-cli']
#     runs-on: ubuntu-latest
#     needs: [build]
#     steps:
#       - name: Repository Dispatch
#         uses: peter-evans/repository-dispatch@v1
#         with:
#           token: ${{ secrets.REPO_ACCESS_TOKEN }}
#           repository: ${{ matrix.repo }}
#           event-type: releaseCli
