name: Cli-core Release
on:
  workflow_dispatch:
    inputs:
      cli-branch:
        description: 'Run workflow in the branch'
        default: main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout cli-core repo
        uses: actions/checkout@v2
      - run: npm install
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run tests
        run: npm test
  update-api-specs:
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      change-log: ${{ steps.update-specs.outputs.change-log }}
      version-type: ${{ steps.update-specs.outputs.version-type }}
    steps:
      - name: Create temporary folder for copying json files fom OAI repo
        run: mkdir -p ~/oai_definitions/json
      - name: Checkout OAI repo
        uses: actions/checkout@v2
        with:
          repository: 'LakshmiRavali/twilio-oai'
          token:  ${{ secrets.OAI_TOKEN }}
      - run: |
          cp -R spec/json/. ~/oai_definitions/json/
          cp -R CHANGES.md ~/oai_definitions/CHANGES.md
      - name: Checkout cli-core repo
        uses: actions/checkout@v2
      - name: Update OAI specs
        id: update-specs
        run: |
          npm install
          cp -R ~/oai_definitions/CHANGES.md OAI_CHANGES.md
          source .github/scripts/update-api-spec-with-changelog.sh
          echo "::set-output name=change-log::$changeLog"
          echo "::set-output name=version-type::$versionType"
        env:
          email: ${{secrets.TWILIO_EMAIL}}
          twilioUser: ${{secrets.TWILIO_USER}}
  release:
    runs-on: ubuntu-latest
    needs: [update-api-specs]
    outputs:
      tag-name: '5.31.0'
    steps:
      - name: Checkout cli-core repo
        uses: actions/checkout@v2
      - run: |
          git pull
          npm install
#       - name: semanticRelease
#         id: semantic-release
#         run: |
#           npm i --save-dev @semantic-release/exec
#           npx semantic-release -t \${version}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update release
        run: node .github/scripts/update-release.js
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: '5.31.0'
          RELEASE_BODY: ${{needs.update-api-specs.outputs.change-log}}
          REPO_NAME: LakshmiRavali/twilio-cli-core
  triggerCliWorkflow:
    runs-on: ubuntu-latest
    needs: [ update-api-specs, release]
    steps:
      - name: Checkout cli-core repo
        uses: actions/checkout@v2
      - run: |
          git pull
          npm install
      - name: Invoke CLI workflow with changelog and version-type
        if: ${{toJSON(needs.update-api-specs.outputs.change-log) != null && needs.update-api-specs.outputs.version-type != '-1'}}
        run: node .github/scripts/trigger-workflow.js
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WORKFLOW_NAME: 'release.yml'
          BRANCH_NAME: ${{github.event.inputs.cli-branch}}
          REPO_NAME: LakshmiRavali/twilio-cli
          INPUTS: '{ "change-log": ${{ toJSON(needs.update-api-specs.outputs.change-log) }}, "version-type": "${{needs.update-api-specs.outputs.version-type}}" }'
